[pytest]
norecursedirs =
    .*
    __pycache__
    htmlcov

pythonpath = "."
python_files = test__*.py
testpaths = tests

addopts = -m "not slow"
markers =
    slow: mark test as slow (wont run by default)
    external: mark tests that use third-party estimators
